// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwGb_6IYuHc5icSE7wkTo1X5Q8oKWHdk',
    appId: '1:44461910225:web:b1fffd082b899dd94e3df0',
    messagingSenderId: '44461910225',
    projectId: 'realtimemonitoring-3a45f',
    authDomain: 'realtimemonitoring-3a45f.firebaseapp.com',
    storageBucket: 'realtimemonitoring-3a45f.firebasestorage.app',
    measurementId: 'G-FEC8G7SJTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWOtlyMRwis1oXx9tJcD2Ewcv66-4mmkQ',
    appId: '1:44461910225:android:584a3cb7afcf8faf4e3df0',
    messagingSenderId: '44461910225',
    projectId: 'realtimemonitoring-3a45f',
    storageBucket: 'realtimemonitoring-3a45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgULB5ZWE9yVEZ8tvY7NAcRkIt4Ym-Kk',
    appId: '1:490567708627:ios:b08c74d7989db58abe0926',
    messagingSenderId: '490567708627',
    projectId: 'fyp2-a23f8',
    databaseURL: 'https://fyp2-a23f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2-a23f8.firebasestorage.app',
    iosBundleId: 'com.example.fyp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHgULB5ZWE9yVEZ8tvY7NAcRkIt4Ym-Kk',
    appId: '1:490567708627:ios:b08c74d7989db58abe0926',
    messagingSenderId: '490567708627',
    projectId: 'fyp2-a23f8',
    databaseURL: 'https://fyp2-a23f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2-a23f8.firebasestorage.app',
    iosBundleId: 'com.example.fyp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFwGb_6IYuHc5icSE7wkTo1X5Q8oKWHdk',
    appId: '1:44461910225:web:aef16c9b59b06d614e3df0',
    messagingSenderId: '44461910225',
    projectId: 'realtimemonitoring-3a45f',
    authDomain: 'realtimemonitoring-3a45f.firebaseapp.com',
    storageBucket: 'realtimemonitoring-3a45f.firebasestorage.app',
    measurementId: 'G-RC3Q74MQ2G',
  );

}